//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.16 at 10:23:11 AM EDT 
//


package edu.stevens.cs.cs548.clinic.schemasecond;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SurgeryTreatmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SurgeryTreatmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/Treatment}TreatmentType">
 *       &lt;sequence>
 *         &lt;element name="surgeryDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SurgeryTreatmentType", propOrder = {
    "surgeryDate"
})
public class SurgeryTreatmentType
    extends TreatmentType
{

    @XmlElement(required = true)
    protected String surgeryDate;

    /**
     * Gets the value of the surgeryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurgeryDate() {
        return surgeryDate;
    }

    /**
     * Sets the value of the surgeryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurgeryDate(String value) {
        this.surgeryDate = value;
    }

}
